name = "marvillverse"
main = "worker/index.ts"
compatibility_date = "2026-10-04"

[assets]
directory = "./dist/marvillverse/browser"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "marvillverse-db"
database_id = "29aa0240-e16d-44a1-a04e-88f52829abfe"
migrations_dir = "worker/migrations"

