INSERT OR REPLACE INTO projects(id,name,tagline,description,category,status,platforms,tech,monogram,accent,progress,version,updated,started,featured,vision,capabilities,github,website,sort_order) VALUES
('veylith','Veylith','Autonomous Development System','A cloud-based autonomous engineering system designed to plan, build, test and continuously develop software.','AI','Building','["Cloud","Web"]','["AI","Node","Git"]','V','#ff4057',68,'0.9.0','2026-09-27','2026-09',1,'An autonomous engineering environment capable of continuously transforming ideas into working software.','["Autonomous planning","Code generation","Build & test cycles","Git operations","Live monitoring"]','https://github.com/marvills-hub/veylith',NULL,1),
('zevryth','Zevryth','AI Image Generation','An intelligent image generation platform focused on turning ideas into high-quality visual creations.','AI','Building','["Web"]','["Angular","AI","Ollama"]','Z','#9b6cff',42,'0.1.0','2026-09-26','2026-09',1,'A visual intelligence system built to transform imagination into generated imagery and eventually motion.','["Image generation","Prompt workspace","Local AI","Generation history","Future animation"]',NULL,NULL,2),
('lexyra','Lexyra','Universal Text Engine','An offline-first text utility with more than a hundred tools for transforming, formatting, generating and processing text.','Productivity','Active','["Web","Desktop"]','["Angular","AI"]','L','#438cff',78,'0.4.0','2026-09-29','2026-09',1,'One powerful environment for manipulating virtually any kind of text with or without artificial intelligence.','["138+ text tools","Offline processing","Formatting engine","Converters","Optional AI"]',NULL,NULL,3),
('notiva','Notiva','Visual Notes & Ideas','A cross-platform visual workspace for notes, ideas, reminders, calendars and creative thinking on an infinite canvas.','Productivity','Building','["Web","Desktop","Mobile"]','["Angular","Tauri","Capacitor"]','N','#e8a86b',74,'0.7.0','2026-09-19','2026-08',0,'A tactile digital space where thoughts can be arranged visually instead of being trapped inside conventional documents.','["Infinite boards","Visual notes","Rich editor","Calendar notes","Cross-platform"]',NULL,'https://notiva-b07f7.web.app/',4),
('notificator','Notificator','Unified Notification Center','A desktop notification aggregator bringing important communication from multiple services into one focused experience.','Productivity','Building','["Desktop"]','["Angular","Tauri","Cloudflare"]','N','#42d9a5',61,'0.6.0','2026-09-06','2026-08',0,'One intelligent notification layer that keeps important communication visible without forcing users between applications.','["Gmail integration","Floating widget","Urgent alerts","Multi-account","Cloud sync"]','https://github.com/marvills-hub/notificator',NULL,5),
('manager','Marvills Manager','Project Management Platform','A multi-workspace project management system for projects, tasks, clients, meetings, notes, diagrams and reporting.','Platform','Active','["Web"]','["Angular","Firebase"]','M','#ffb84d',82,'1.0.0','2026-09-01','2025',0,'A unified workspace for managing the complete lifecycle of projects, teams, clients and everyday work.','["Projects & tasks","Client management","Meetings","Time tracking","Reports"]',NULL,NULL,6),
('ceonix','Ceonix','CEOSI Internal Super-App','An internal employee platform combining communication, voting, meal decisions and expandable company tools.','Internal','Building','["Web","Desktop","Mobile"]','["Angular","Tauri","Capacitor"]','C','#39c7ff',34,'0.1.0','2026-10-03','2026-10',0,'A single internal digital home for everyday collaboration and employee tools across CEOSI.','["Team chat","Polls & voting","Meal decisions","Internal tools","Multi-platform"]',NULL,NULL,7);

INSERT INTO activities(project_id,date,title,description,type) VALUES
('ceonix','2026-10-03','Ceonix enters development','Initial multi-platform internal application foundation established.','Milestone'),
('lexyra','2026-09-29','138 tools registered','Lexyra tool registry reached 138 verified text utilities.','Milestone'),
('veylith','2026-09-27','Autonomous runtime online','Persistent job runtime and autonomous development pipeline progressed.','Development'),
('zevryth','2026-09-26','Local AI direction','Image generation architecture moved toward local Ollama-powered workflows.','Development'),
('notiva','2026-09-19','Visual editor expanded','Board, notes, calendar and rich text editing continued evolving.','Development'),
('notificator','2026-09-06','Gmail restore operational','Gmail connection and restoration flow became operational.','Milestone');
